/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhirooprpl.GUI;

/**
 *
 * @author fadil
 */
public class form_periksa extends javax.swing.JFrame {

    /**
     * Creates new form form_periksa
     */
    public form_periksa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama_klinik = new javax.swing.JLabel();
        nama_rs = new javax.swing.JLabel();
        nama_dokter = new javax.swing.JLabel();
        lbl_shift = new javax.swing.JLabel();
        lbl_perawat = new javax.swing.JLabel();
        lbl_perawat1 = new javax.swing.JLabel();
        lbl_perawat2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        background_periksa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_klinik.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        nama_klinik.setForeground(new java.awt.Color(112, 112, 112));
        nama_klinik.setText("Klinik . . . . . . . . . ");
        getContentPane().add(nama_klinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 680, -1));

        nama_rs.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nama_rs.setForeground(new java.awt.Color(112, 112, 112));
        nama_rs.setText("Rumah Sakit Al-Boromeous");
        getContentPane().add(nama_rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        nama_dokter.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        nama_dokter.setForeground(new java.awt.Color(112, 112, 112));
        nama_dokter.setText("Dokter  : Dr. Broto Asmoro uwu");
        getContentPane().add(nama_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        lbl_shift.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_shift.setForeground(new java.awt.Color(112, 112, 112));
        lbl_shift.setText("Shift   : Pagi");
        getContentPane().add(lbl_shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 290, -1));

        lbl_perawat.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_perawat.setForeground(new java.awt.Color(112, 112, 112));
        lbl_perawat.setText("Perawat : ");
        getContentPane().add(lbl_perawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 100, -1));

        lbl_perawat1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_perawat1.setForeground(new java.awt.Color(112, 112, 112));
        lbl_perawat1.setText("1. ABCDEFGHIJKL");
        getContentPane().add(lbl_perawat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 70, 210, -1));

        lbl_perawat2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_perawat2.setForeground(new java.awt.Color(112, 112, 112));
        lbl_perawat2.setText("2. LKJIHGFEDCBA");
        getContentPane().add(lbl_perawat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, 210, -1));

        jPanel1.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Deskripsi", "Keterangan"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setOpaque(false);
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Deskripsi");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Keterangan");
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Component 7 – 1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pemeriksaan", jPanel1);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1378, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1380, 660));

        background_periksa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Web 1920 – 5.png"))); // NOI18N
        getContentPane().add(background_periksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.addRowSelectionInterval(1, jTable1.getRowCount() +1 );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_periksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_periksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_periksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_periksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_periksa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_periksa;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_perawat;
    private javax.swing.JLabel lbl_perawat1;
    private javax.swing.JLabel lbl_perawat2;
    private javax.swing.JLabel lbl_shift;
    private javax.swing.JLabel nama_dokter;
    private javax.swing.JLabel nama_klinik;
    private javax.swing.JLabel nama_rs;
    // End of variables declaration//GEN-END:variables
}
