/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhirooprpl.GUI;

/**
 *
 * @author fadil
 */
public class login2 extends javax.swing.JFrame {

    /**
     * Creates new form login2
     */
    public login2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama_klinik = new javax.swing.JLabel();
        nama_rs = new javax.swing.JLabel();
        nama_dokter = new javax.swing.JLabel();
        lbl_shift = new javax.swing.JLabel();
        lbl_perawat = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        btn_set = new javax.swing.JButton();
        field_idpasien = new javax.swing.JTextField();
        field_prwt1 = new javax.swing.JTextField();
        field_prwt2 = new javax.swing.JTextField();
        background_login2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 870));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_klinik.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        nama_klinik.setForeground(new java.awt.Color(112, 112, 112));
        nama_klinik.setText("Klinik . . . . . . . . . ");
        getContentPane().add(nama_klinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 680, -1));

        nama_rs.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nama_rs.setForeground(new java.awt.Color(112, 112, 112));
        nama_rs.setText("Rumah Sakit Al-Boromeous");
        getContentPane().add(nama_rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        nama_dokter.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        nama_dokter.setForeground(new java.awt.Color(112, 112, 112));
        nama_dokter.setText("Dokter  : Dr. Broto Asmoro uwu");
        getContentPane().add(nama_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        lbl_shift.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_shift.setForeground(new java.awt.Color(112, 112, 112));
        lbl_shift.setText("Shift   : ");
        getContentPane().add(lbl_shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 290, -1));

        lbl_perawat.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbl_perawat.setForeground(new java.awt.Color(112, 112, 112));
        lbl_perawat.setText("Perawat : ");
        getContentPane().add(lbl_perawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 100, -1));

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Component 3 – 1.png"))); // NOI18N
        btn_next.setBorder(null);
        btn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        btn_set.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Component 2 – 1.png"))); // NOI18N
        btn_set.setBorder(null);
        btn_set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_set, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, -1, -1));

        field_idpasien.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(field_idpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 230, 30));

        field_prwt1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(field_prwt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 230, 30));

        field_prwt2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(field_prwt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, 230, 30));

        background_login2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Web 1920 – 3.png"))); // NOI18N
        getContentPane().add(background_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_login2;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_set;
    private javax.swing.JTextField field_idpasien;
    private javax.swing.JTextField field_prwt1;
    private javax.swing.JTextField field_prwt2;
    private javax.swing.JLabel lbl_perawat;
    private javax.swing.JLabel lbl_shift;
    private javax.swing.JLabel nama_dokter;
    private javax.swing.JLabel nama_klinik;
    private javax.swing.JLabel nama_rs;
    // End of variables declaration//GEN-END:variables
}
